# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: << pipeline.parameters.run-setup >>

parameters:
  run-setup:
    description: Whether it is a setup workflow or a continuation
    type: boolean
    default: true
  force-all:
    description: Emergency valve - forcibly build all the modules
    type: boolean
    default: false
  dynamic-config-base-revision:
    description: Base revision to consider for setup workflow
    type: string
    default: << pipeline.git.base_revision >>

commands:
  common-tasks:
    parameters:
      branch:
        description: Current build branch
        type: string
        default: ""
      tag:
        description: Current build tag
        type: string
        default: ""
    steps:
      - run: echo 'Branch << parameters.branch >>'
      - run: echo 'Tag << parameters.tag >>'

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello prod"
          command: "echo Hello, World!"      

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  # say-hello-workflow:
  #   jobs:
  #     - say-hello
  setup-workflow:
    when: << pipeline.parameters.run-setup >>
    jobs:
      - config-splitting/setup-dynamic-config:
          name: config-splitting/setup-dynamic-config-dev
          force-all: << pipeline.parameters.force-all >>
          base-revision: main
          # If A is modified, the job for A will run
          # Similarly if B is modified, the job for B will run
          # If C is modified, then the jobs for both C and B (as a dependency) will run
          modules: |
            module1
            module2
          filters:
            branches:
              only: /^.*+$/
            tags:
              ignore: /.*/
      - config-splitting/setup-dynamic-config:
          name: config-splitting/setup-dynamic-config-prod
          force-all: true
          base-revision: main
          # If A is modified, the job for A will run
          # Similarly if B is modified, the job for B will run
          # If C is modified, then the jobs for both C and B (as a dependency) will run
          modules: |
            module1
            module2
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

orbs:
  python: circleci/python@1.5.0

  # An "embedded" orb to facilitate config splitting
  config-splitting:
    # Dependencies
    orbs:
      continuation: circleci/continuation@0.1.2
    # Commands for the setup workflow
    commands:
      list-changed-modules:
        parameters:
          modules:
            description: |
              Directories which should be built upon changes.
              Each row represents a space-separated list of the root directories for modules, each of which must has own `.circleci/config.yml`.
              The first item of the list will be tested for changes, and will be added to the filtered list of modules if there are any changes.
              The subsequent items, if there are any, will also be added to the filtered list of modules if there are any changes in the directory specified as the first item.

              CAVEAT: Directory names having white spaces cannot be specified.
            type: string
          modules-filtered:
            description: Path to the file where the filtered list of modules is generated
            type: string
            default: /tmp/modules-filtered.txt
          base-revision:
            description: Revision to compare with the current HEAD
            type: string
            default: main
          force-all:
            description: Emergency valve - forcibly build all the modules
            type: boolean
            default: false
        steps:
          - run:
              name: Generate the list of modules having changes
              command: |
                # Add each module to `modules-filtered` if 1) `force-all` is set to `true`, 2) there is a diff against `base-revision`, 3) there is no `HEAD~1` (i.e., this is the very first commit for the repo) OR 4) there is a diff against the previous commit
                cat \<< EOD | sed -e '/^$/d' | while read row; do module="$(echo "$row" | awk '{ print $1 }')"; if [ << parameters.force-all >> == 'true' ] || [ $(git diff --name-only << parameters.base-revision >> "$module" | wc -l) -gt 0 ] || (! git rev-parse --verify HEAD~1) || [ $(git diff --name-only HEAD~1 "$module" | wc -l) -gt 0 ]; then echo "$row" | sed -e 's/ /\n/g' >> << parameters.modules-filtered >>; fi; done
                << parameters.modules >>
                EOD

      merge-modular-configs:
        parameters:
          modules:
            description: Path to the file for the list of the modules to build
            type: string
            default: /tmp/modules-filtered.txt
          shared-config:
            description: Path to the config providing shared resources (such as prerequisite jobs and common commands)
            type: string
            default: .circleci/config.yml
          continue-config:
            description: Path to the internally-used config for continuation
            type: string
            default: .circleci/continue-config.yml
        steps:
          - run:
              name: Merge configs
              command: |
                # If `modules` is unavailable, stop this job without continuation
                if [ ! -f "<< parameters.modules >>" ] || [ ! -s "<< parameters.modules >>" ]
                then
                  echo 'Nothing to merge. Halting the job.'
                  circleci-agent step halt
                  exit
                fi

                # Convert a list of dirs to a list of config.yml
                sed -i -e 's/$/\/.circleci\/config.yml/g' "<< parameters.modules >>"

                # If `shared-config` exists, append it at the end of `modules`
                if [ -f << parameters.shared-config >> ]
                then
                  echo "<< parameters.shared-config >>" >> "<< parameters.modules >>"
                fi

                xargs -a "<< parameters.modules >>" yq -y -s 'reduce .[] as $item ({}; . * $item)' | tee "<< parameters.continue-config >>"
    jobs:
      # The job for the setup workflow
      setup-dynamic-config:
        parameters:
          modules:
            description: Directories which should be tested for changes; one directory per line. Each directory must have `.circleci/config.yml`.
            type: string
          base-revision:
            description: Revision to compare with the current HEAD
            type: string
            default: main
          force-all:
            description: Emergency valve - forcibly build all the modules
            type: boolean
            default: false
          modules-filtered:
            description: Path to the file where the filtered list of modules is generated
            type: string
            default: /tmp/modules-filtered.txt
          shared-config:
            description: Path to the config providing shared resources (such as prerequisite jobs and common commands)
            type: string
            default: .circleci/config.yml
          continue-config:
            description: Path to the internally-used config for continuation
            type: string
            default: .circleci/continue-config.yml
        docker:
          - image: cimg/python:3.9
        steps:
          - run:
              name: Test Dynamic-config-base-revision
              command: echo 'Dynamic-config-base-revision << pipeline.parameters.dynamic-config-base-revision >>'
          - checkout
          - run:
              name: Install yq
              command: pip install yq
          - list-changed-modules:
              modules: << parameters.modules >>
              modules-filtered: << parameters.modules-filtered >>
              base-revision: << parameters.base-revision >>
              force-all: << parameters.force-all >>
          - merge-modular-configs:
              modules: << parameters.modules-filtered >>
              shared-config: << parameters.shared-config >>
              continue-config: << parameters.continue-config >>
          - continuation/continue:
              configuration_path: << parameters.continue-config >>
              parameters: '{"run-setup":false}'
