version: 2.1

workflows:
  module1-say-hello-workflow:
    jobs:
      - say-hello-prod:
          name: module1-say-hello-prod
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - say-hello-dev:
          name: module1-say-hello-dev
          filters:
            branches:
              only: /^.*+$/
            tags:
              ignore: /.*/
